### ISSUE TITLE
Only One Typo found

### ISSUE THREAD

**Issue by molliapu** [pszucs/TypoFinder#1]
Hi Peter,

When I save document and if there are more typo can be found, the plugin repairs only one, after I have to save the document again.

**Comment by pszucs** [comment]
Hi @molliapu,

1. Is it the same typo or another one?
2. What's in your settings file?
3. What is the typo that you think the script should fix?

**Comment by molliapu** [comment]
Tha was not an empty space before the comma, maybe it is phpcs error, i
donnu don't remember exactly.

**Comment by pszucs** [comment]
Can you replicate the issue?

**Comment by molliapu** [comment]
Unfortunately no.
After this situation the problem has gone.
I'll inform You next time when I'll have again.
